name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      # - name: github-metrics
      #   uses: lowlighter/metrics@latest
      #   with:
      #     token: ${{ secrets.METRIC_API }}
      # - name: Full-year calendar
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.isocalendar.fullyear.svg
      #     token: ${{ secrets.METRIC_API }}
      #     base: ""
      #     plugin_isocalendar: yes
      #     plugin_isocalendar_duration: full-year
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRIC_API }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      # - name: Using classic charts
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.stargazers.svg
      #     token: ${{ secrets.METRIC_API }}
      #     base: ""
      #     plugin_stargazers: yes

  
