name: WakaTime Readme

on:
  push:
    branches:
      - master
  schedule:
   - cron: "0 */2 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.2.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
